volumes:
  pages: http://www.comicvine.com/api/volumes/?format=json&api_key={apiKey}&offset={offset}&sort=date_last_updated:asc
  metadata: http://www.comicvine.com/api/volumes/?format=json&api_key={apiKey}&limit=1&sort=date_last_updated:desc&field_list=date_last_updated
issues:
  pages: http://www.comicvine.com/api/issues/?format=json&api_key={apiKey}&offset={offset}&sort=date_last_updated:asc
  metadata: http://www.comicvine.com/api/issues/?format=json&api_key={apiKey}&limit=1&sort=date_last_updated:desc&field_list=date_last_updated
apiKey: ebc22acd94902b6b8b1746df3648ef875d4e6dae
jerseyClient:
  timeout: 30000ms
  connectionTimeout: 30000ms
logging:
  level: INFO
  loggers:
    "com.github.nordinh.comicollector.comicvine": DEBUG
mongo:
  uri: mongodb://localhost:27017/?maxPoolSize=5&maxIdleTimeMS=300000
  dbName: comiCollection
